on:
    # Only on pushes to master or one of the release branches we build on push
    push:
      branches:
        - main
        - '**'
      tags:
        - '**'

name: Cross Build

jobs:
  cross:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - aarch64-unknown-linux-musl
          - armv7-unknown-linux-musleabihf
          - i686-unknown-linux-musl
          - x86_64-unknown-linux-musl
    name: ${{ matrix.target }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target=${{ matrix.target }}
      - name: Archive barnacle binary
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.target }}
          path: |
            target/${{ matrix.target }}/release/barnacle

  docker:
    runs-on: ubuntu-latest
    needs: cross
    name: Build Docker Containers
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          path: ci/docker/artifacts/
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      # - name: Login to DockerHub
      #   uses: docker/login-action@v1
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build docker containers
        uses: docker/build-push-action@v2
        with:
          context: ci/docker/
          push: false
          tags: bertjwregeer/barnacle:latest
          platforms: linux/amd64,linux/386,linux/arm64,linux/arm/v7
